### PR TITLE
Add `crossProjectCrossType`, `crossProjectBaseDirectory` settings

### PR DESCRIPTION
**Pull request by armanbilge**
Exposing these will be helpful for introspection in downstream plugins. Thanks!

### CODE REVIEW

**Comment by armanbilge** [comment]
Scala.js tests are failing probably because CI updated to Node.js 18.

**Comment by sjrd** [comment]
Could you tell a bit more about what the actual use cases are?

**Comment by armanbilge** [comment]
Sure :)

1. In the [TypelevelSettingsPlugin](https://github.com/typelevel/sbt-typelevel/blob/352d401af55924b4f552803bb98cda241c715d30/settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala#L263-L264) we are iterating over all cross-types because we don't know the applicable one.
2. In the [MergifyPlugin](https://github.com/typelevel/sbt-typelevel/blob/352d401af55924b4f552803bb98cda241c715d30/mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyPlugin.scala#L155-L160) we are using heuristics to try and figure out the base directory for cross projects.
3. In the [BspControlPlugin](https://github.com/typelevel/sbt-typelevel/pull/465) we want to use the `CrossType` to decide whether to enable BSP for all platforms or not.
4. In the [CluePlugin](https://github.com/gemini-hlsw/clue/blob/bcfd8369ad2582a5c7a20d29b69c2a71714f1366/sbt-plugin/src/main/scala/clue/sbt/CluePlugin.scala#L28) we want to read GraphQL schemas from a folder under the effective base directory.

**Comment by sjrd** [comment]
Thanks, and sorry for the late reply. That series of use seems rather compelling, indeed.

**Comment by sjrd** [comment]
I fixed the CI in #153. Could you rebase, please?

**Comment by armanbilge** [comment]
No problem at all, thanks for fixing CI! :)

**Review by sjrd — APPROVED** [review]

**Pull request merged**
