### PR TITLE
Composite project

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by BennyHill** [comment]
Perhaps bump to RC2?

**Comment by BennyHill** [comment]
So now that SBT 1.2 is released....could this be merged and released, please? Not urgent for me...just asking. Thanks!!

**Comment by nafg** [comment]
Probably should bump to 1.2.1: https://developer.lightbend.com/blog/2018-08-07-sbt-1-2-1/index.html#forward-bincompat-breakage

**Comment by sjrd** [comment]
I don't see why. Since sbt-crossproject uses `CompositeProject`, it will not be usable from sbt 1.0.x nor 1.1.x anyway.

**Pull request merged**
