### PR TITLE
Scala 2.12.10

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sjrd** [comment]
The CI was broken on master. If fixed it in #120. Could you rebase on top of the latest master, please?

**Comment by sjrd** [comment]
Ah, sorry, it looks like I had made another mistake (see https://github.com/portable-scala/sbt-crossproject/pull/121). Could you rebase once more, please?

**Comment by sjrd** [comment]
The CLA check says:
```
Pull request submitted by sullis
CLA check for sullis failed
Please sign the Scala CLA to contribute to sbt-crossproject.
Go to https://www.lightbend.com/contribute/cla/scala and then
comment on the pull request to ask for a new check.
```

**Comment by sullis** [comment]
please re-check CLA

**Pull request merged**
