### PR TITLE
JVMNoSuffix removes the suffix JVM on sbt projects

### PR DESCRIPTION
**Pull request by MasseGuillaume**
Context: https://stackoverflow.com/questions/46271505/how-do-i-change-a-projects-id-in-sbt-1-0/46276523#46276523

### CODE REVIEW

**Comment by sjrd** [comment]
I ... er ... that was not the point :( This bastardizes `JVMCrossProjectOps`.

**Comment by MasseGuillaume** [comment]
Maybe it could be without the suffix since Scala.js 1.0.0 would allow this kind of changes. I think it's super useful to avoid those extra keystrokes. it also does not change the project name for a library adding crossProject capability.

**Comment by sjrd** [comment]
> it also does not change the project name for a library adding crossProject capability.

`crossProject` does not change project *names*. Only the IDs.

sbt-crossproject is supposed not to have any bias for or against any of the platforms.

**Comment by MasseGuillaume** [comment]
We (@sjrd and I) decided to put this PR on hold.

@sjrd suggested defining a default platform that does not have the suffix:

```scala
crossProject(JSPlatform, JVMPlatform)
  .withDefault(
    JVMPlatform // or JSPlatform
  )
```

I suggest creating a non-biased pool to decide if we should set a default platform by default. For example, have the JVMPlatform as default.

**Comment by sjrd** [comment]
I think the no-default-platform-by-default is technically superior:

* It is unbiased: it doesn't debase a core design principle of sbt-crossproject
* It is explicit: it is easier to know what's going on when I read a build; there is less magic
* It is backwards compatible (not only with Scala.js 0.6.x, but also with sbt-crossproject 0.2.x which is already used by people)

**Pull request closed without merging**
