### PR TITLE
update README

### PR DESCRIPTION
**Pull request by note**

### CODE REVIEW

**Comment by sjrd** [comment]
The CI says:
```
Incoming pull request from https://github.com/portable-scala/sbt-crossproject/pull/77
Pull request submitted by note
CLA check for note failed
Please sign the Scala CLA to contribute to sbt-crossproject
Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request
```

**Comment by note** [comment]
@sjrd forced pushed same commit with using different email (one which I've signed CLA before)

**Comment by sjrd** [comment]
@densh The CLA check on the CI seems bogus. It still says that @note has not signed the CLA, but https://www.lightbend.com/contribute/cla/scala/check/nope shows `"signed":true`.

**Comment by densh** [comment]
@sjrd I've restarted the build once again and it seems to be working now.

**Pull request merged**
